"use client";

import { Bell, Check, ChevronRight, Clock3, Dumbbell, Flag, Heart, LoaderCircle, LockKeyhole, MessageCircle, MoreHorizontal, Pin, Plus, Search, Send, Trash2, UsersRound, X } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { usePathname, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useRef, useState, useTransition } from "react";
import { createCommunityCommentAction, deleteCommunityCommentAction, deleteCommunityPostAction, loadCommunityCommentsAction, loadCommunityFeedPageAction, markCommunityNotificationsReadAction, moderateCommunityContentAction, pinCommunityPostAction, reportCommunityContentAction, requestOrJoinCommunityGroupAction, searchCommunityGroupsAction, setCommunityLikeAction, updateCommunityPostAction } from "@/app/actions/community";
import { CommunityComposer } from "@/components/community/CommunityComposer";
import { Avatar } from "@/components/ui/PPerfilPrimitives";
import type { CommunityComment, CommunityGroup, CommunityPost, CommunityWorkspace } from "@/lib/domain/community";

type Tab = "feed" | "groups";
const relative = new Intl.RelativeTimeFormat("pt-BR", { numeric: "auto" });
function relativeDate(value: string) { const seconds = Math.round((new Date(value).getTime() - Date.now()) / 1000); const absolute = Math.abs(seconds); if (absolute < 60) return "agora"; if (absolute < 3600) return relative.format(Math.round(seconds / 60), "minute"); if (absolute < 86400) return relative.format(Math.round(seconds / 3600), "hour"); return relative.format(Math.round(seconds / 86400), "day"); }
function membershipLabel(group: CommunityGroup) { if (group.membershipStatus === "ACTIVE") return "Membro"; if (group.membershipStatus === "INVITED") return "Convite"; if (group.membershipStatus === "PENDING") return "Solicitado"; return group.joinPolicy === "OPEN" ? "Entrar" : group.joinPolicy === "APPROVAL" ? "Solicitar" : "Por convite"; }
function persistKey(audience: "trainer" | "student") { return `cheipi.community.${audience}.v1`; }

export function CommunityFeed({ workspace, audience, shareWorkoutExecutionId }: { workspace: CommunityWorkspace; audience: "trainer" | "student"; shareWorkoutExecutionId?: string }) {
  const pathname = usePathname(), searchParams = useSearchParams();
  const [tab, setTab] = useState<Tab>(searchParams.get("tab") === "groups" ? "groups" : "feed");
  const [posts, setPosts] = useState(workspace.posts), [groups, setGroups] = useState(workspace.discovery), [query, setQuery] = useState("");
  const [nextCursor, setNextCursor] = useState(workspace.nextCursor), [loadingMore, setLoadingMore] = useState(false), [composerOpen, setComposerOpen] = useState(Boolean(shareWorkoutExecutionId));
  const [message, setMessage] = useState<string | null>(null), [notificationsOpen, setNotificationsOpen] = useState(false), [pending, startTransition] = useTransition();
  const loadMoreRef = useRef<HTMLDivElement>(null), searchSequence = useRef(0), restored = useRef(false);
  const activeGroups = useMemo(() => workspace.groups.filter((group) => group.membershipStatus === "ACTIVE"), [workspace.groups]);
  const unread = workspace.notifications.filter((item) => !item.readAt).length;

  useEffect(() => {
    const saved = sessionStorage.getItem(persistKey(audience));
    if (!saved || restored.current) return;
    restored.current = true;
    try { const value = JSON.parse(saved) as { tab?: Tab; scrollY?: number }; requestAnimationFrame(() => { if (value.tab) setTab(value.tab); scrollTo({ top: value.scrollY ?? 0 }); }); } catch { /* stale state is intentionally ignored */ }
  }, [audience]);
  useEffect(() => { const save = () => sessionStorage.setItem(persistKey(audience), JSON.stringify({ tab, scrollY })); addEventListener("pagehide", save); return () => { save(); removeEventListener("pagehide", save); }; }, [audience, tab]);

  const changeTab = (value: Tab) => { setTab(value); setMessage(null); const params = new URLSearchParams(searchParams.toString()); if (value === "feed") params.delete("tab"); else params.set("tab", value); history.replaceState(history.state, "", `${pathname}${params.size ? `?${params}` : ""}`); };
  const loadMore = useCallback(async () => {
    if (!nextCursor || loadingMore) return;
    setLoadingMore(true); const result = await loadCommunityFeedPageAction(nextCursor); setLoadingMore(false);
    if (!result.ok || !result.data) { setMessage(result.message); return; }
    setPosts((current) => [...current, ...result.data!.filter((item) => !current.some((known) => known.id === item.id))]);
    const last = result.data.at(-1); setNextCursor(result.data.length === 15 && last ? { publishedAt: last.publishedAt, id: last.id } : null);
  }, [loadingMore, nextCursor]);
  useEffect(() => { const target = loadMoreRef.current; if (!target) return; const observer = new IntersectionObserver((entries) => { if (entries[0]?.isIntersecting) void loadMore(); }, { rootMargin: "480px" }); observer.observe(target); return () => observer.disconnect(); }, [loadMore]);
  useEffect(() => { if (tab !== "groups") return; const sequence = ++searchSequence.current; const timeout = setTimeout(() => startTransition(async () => { const result = await searchCommunityGroupsAction(query.trim()); if (sequence === searchSequence.current && result.ok && result.data) setGroups(result.data); }), 260); return () => clearTimeout(timeout); }, [query, tab]);

  function openNotifications() { setNotificationsOpen(true); if (unread) startTransition(async () => { await markCommunityNotificationsReadAction(workspace.notifications.filter((item) => !item.readAt).map((item) => item.id)); }); }
  function created(post?: CommunityPost, feedback?: string) { if (post) setPosts((current) => [post, ...current.filter((item) => item.id !== post.id)]); setMessage(feedback ?? "Publicado na Comunidade."); }
  if (workspace.unavailableReason === "ENTITLEMENT") return <CommunityState icon={<LockKeyhole />} title="Comunidade indisponível no seu acesso atual" body="Os grupos e conteúdos permanecem preservados e voltam quando o acesso for reativado." />;
  if (workspace.unavailableReason === "ERROR") return <CommunityState icon={<X />} title="Não foi possível abrir a Comunidade" body="Tente novamente em instantes. Seus grupos e publicações permanecem seguros." action={<button type="button" onClick={() => location.reload()}>Tentar novamente</button>} />;

  return <div className={`community-page community-page--${audience}`}>
    <header className="community-topbar"><div><span>Cheipi</span><h1>Comunidade</h1></div><button type="button" className="community-icon-button" onClick={openNotifications} aria-label={unread ? `${unread} notificações não lidas` : "Notificações"}><Bell aria-hidden="true" />{unread ? <b>{unread > 9 ? "9+" : unread}</b> : null}</button></header>
    <nav className="community-tabs" aria-label="Navegação da Comunidade"><button type="button" aria-current={tab === "feed" ? "page" : undefined} onClick={() => changeTab("feed")}>Feed</button><button type="button" aria-current={tab === "groups" ? "page" : undefined} onClick={() => changeTab("groups")}>Grupos</button></nav>
    {message ? <div className="community-feedback" role="status"><span>{message}</span><button type="button" onClick={() => setMessage(null)} aria-label="Fechar mensagem"><X aria-hidden="true" /></button></div> : null}
    {tab === "feed" ? <>{posts.length ? <section className="community-feed" aria-label="Feed dos seus grupos">{posts.map((post) => <CommunityPostCard key={post.id} post={post} audience={audience} onChange={(next) => setPosts((current) => current.map((item) => item.id === next.id ? next : item))} onRemove={(id) => setPosts((current) => current.filter((item) => item.id !== id))} onMessage={setMessage} />)}</section> : <CommunityState icon={<UsersRound />} title={activeGroups.length ? "Seu feed começa aqui" : "Encontre seu primeiro grupo"} body={activeGroups.length ? "As publicações dos seus grupos aparecerão neste espaço." : "Explore grupos de treino e participe da conversa."} action={<button type="button" onClick={() => changeTab("groups")}>Explorar grupos</button>} />}<div ref={loadMoreRef} className="community-feed-sentinel" aria-live="polite">{loadingMore ? <><LoaderCircle className="community-spin" aria-hidden="true" />Carregando publicações</> : null}</div></> : <CommunityGroups audience={audience} mine={workspace.groups} discovery={groups} query={query} pending={pending} onQuery={setQuery} onMessage={setMessage} />}
    {activeGroups.some((group) => group.canPost) ? <button type="button" className="community-fab" onClick={() => setComposerOpen(true)} aria-label="Criar publicação"><Plus aria-hidden="true" /></button> : null}
    <CommunityComposer open={composerOpen} groups={workspace.groups} audience={audience} shareWorkoutExecutionId={shareWorkoutExecutionId} onClose={() => setComposerOpen(false)} onCreated={created} />
    {notificationsOpen ? <div className="community-sheet-layer" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && setNotificationsOpen(false)}><section className="community-sheet" role="dialog" aria-modal="true" aria-labelledby="community-notifications-title"><header><h2 id="community-notifications-title">Notificações</h2><button type="button" onClick={() => setNotificationsOpen(false)} aria-label="Fechar"><X aria-hidden="true" /></button></header>{workspace.notifications.length ? <ul>{workspace.notifications.map((item) => <li key={item.id}><span className={!item.readAt ? "is-unread" : undefined} /><div><strong>{notificationText(item.type)}</strong><p>{item.actorName ? `${item.actorName} · ` : ""}{item.groupName}</p><small>{relativeDate(item.createdAt)}</small>{item.type === "JOIN_REQUEST" ? <Link href={`${audience === "trainer" ? "/dashboard/community" : "/student/community"}/groups/${item.groupId}/manage`}>Revisar solicitação</Link> : null}</div></li>)}</ul> : <CommunityState icon={<Bell />} title="Tudo em dia" body="Novos convites e interações aparecerão aqui." />}</section></div> : null}
  </div>;
}

function CommunityGroups({ audience, mine, discovery, query, pending, onQuery, onMessage }: { audience: "trainer" | "student"; mine: CommunityGroup[]; discovery: CommunityGroup[]; query: string; pending: boolean; onQuery: (value: string) => void; onMessage: (value: string) => void }) {
  const base = audience === "trainer" ? "/dashboard/community/groups" : "/student/community/groups";
  const mineIds = new Set(mine.map((group) => group.id)); const suggestions = discovery.filter((group) => !mineIds.has(group.id));
  const ownedStudentGroup = audience === "student" ? mine.find((group) => group.ownerProductRole === "STUDENT" && group.membershipRole === "OWNER") : undefined;
  const groupAction = audience === "student"
    ? <Link href={ownedStudentGroup ? `${base}/${ownedStudentGroup.id}` : `${base}/new`} className="community-inline-action"><Plus aria-hidden="true" />{ownedStudentGroup ? "Seu grupo" : "Crie seu grupo"}</Link>
    : <Link href={`${base}/new`} className="community-inline-action"><Plus aria-hidden="true" />Criar grupo</Link>;
  return <div className="community-groups-view"><label className="community-search"><Search aria-hidden="true" /><span className="sr-only">Buscar grupos</span><input type="search" value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Buscar grupos ou Personal" /></label>
    <section><header><div><span>Seu espaço</span><h2>Meus grupos</h2></div>{groupAction}</header>{mine.length ? <div className="community-group-grid">{mine.map((group) => <CommunityGroupCard key={group.id} group={group} href={`${base}/${group.id}`} />)}</div> : <p className="community-section-empty">Você ainda não participa de nenhum grupo.</p>}</section>
    <section><header><div><span>Descubra</span><h2>{query ? "Resultados" : "Grupos para você"}</h2></div></header>{pending ? <div className="community-group-skeletons" role="status" aria-label="Buscando grupos"><i /><i /><i /></div> : suggestions.length ? <div className="community-group-list">{suggestions.map((group) => <div key={group.id} className="community-discovery-row"><CommunityGroupCard group={group} href={`${base}/${group.id}`} compact /><button type="button" disabled={group.membershipStatus === "PENDING" || group.joinPolicy === "INVITE_ONLY"} onClick={() => { if (membershipLabel(group) === "Por convite") return; void requestOrJoinCommunityGroupAction(group.id).then((result) => onMessage(result.message)); }}>{membershipLabel(group)}</button></div>)}</div> : <p className="community-section-empty">Nenhum grupo encontrado.</p>}</section>
  </div>;
}

export function CommunityGroupCard({ group, href, compact = false }: { group: CommunityGroup; href: string; compact?: boolean }) {
  return <Link href={href} className={`community-group-card${compact ? " is-compact" : ""}`} onClick={() => sessionStorage.setItem("cheipi.community.returnScroll", String(scrollY))}>{group.avatarUrl ? <Image src={group.avatarUrl} alt="" width={compact ? 64 : 240} height={compact ? 64 : 160} sizes={compact ? "64px" : "(max-width: 767px) 44vw, 220px"} unoptimized /> : <span className="community-group-fallback" aria-hidden="true"><Dumbbell /></span>}<div><span>{group.visibility === "PRIVATE" ? <><LockKeyhole aria-hidden="true" />Privado</> : "Grupo"}</span><h3>{group.name}</h3><p>{group.description || `Com ${group.owner.name}`}</p><small>{group.memberCount} {group.memberCount === 1 ? "membro" : "membros"} · {membershipLabel(group)}</small></div><ChevronRight aria-hidden="true" /></Link>;
}

export function CommunityPostCard({ post, audience, expanded = false, onChange, onRemove, onMessage }: { post: CommunityPost; audience: "trainer" | "student"; expanded?: boolean; onChange: (post: CommunityPost) => void; onRemove: (id: string) => void; onMessage: (message: string) => void }) {
  const [pending, startTransition] = useTransition(), [menuOpen, setMenuOpen] = useState(false), [dialog, setDialog] = useState<"edit" | "delete" | "hide" | "report" | null>(null), [editBody, setEditBody] = useState(post.body ?? "");
  const [comments, setComments] = useState(post.comments), [commentBody, setCommentBody] = useState(""), [commentsOpen, setCommentsOpen] = useState(expanded), [confirmComment, setConfirmComment] = useState<CommunityComment | null>(null);
  const base = audience === "trainer" ? "/dashboard/community" : "/student/community"; const groupBase = `${base}/groups/${post.group.id}`;
  function like() { const before = post; const next = { ...post, likedByMe: !post.likedByMe, likeCount: Math.max(0, post.likeCount + (post.likedByMe ? -1 : 1)) }; onChange(next); startTransition(async () => { const result = await setCommunityLikeAction(post.id, next.likedByMe, crypto.randomUUID()); if (!result.ok) { onChange(before); onMessage(result.message); } else if (result.data) onChange({ ...next, likedByMe: result.data.liked, likeCount: result.data.likeCount }); }); }
  function addComment() { const body = commentBody.trim(); if (!body) return; const mutationId = crypto.randomUUID(); const optimistic: CommunityComment = { id: mutationId, body, createdAt: new Date().toISOString(), authorUserId: "current", authorName: "Você", authorImageUrl: null, canDelete: true, canModerate: false, optimistic: true }; setCommentBody(""); setCommentsOpen(true); setComments((current) => [...current, optimistic]); onChange({ ...post, commentCount: post.commentCount + 1 }); startTransition(async () => { const result = await createCommunityCommentAction(post.id, body, mutationId); if (!result.ok) { setComments((current) => current.filter((item) => item.id !== mutationId)); onChange(post); onMessage(result.message); } else if (result.data) setComments((current) => current.map((item) => item.id === mutationId ? { ...item, id: result.data!.id, createdAt: result.data!.createdAt, optimistic: false } : item)); }); }
  async function showAllComments() { setCommentsOpen(true); const result = await loadCommunityCommentsAction(post.id); if (result.ok && result.data) setComments(result.data); else onMessage(result.message); }
  function removeComment(comment: CommunityComment) { const previous = comments; setConfirmComment(null); setComments((current) => current.filter((item) => item.id !== comment.id)); onChange({ ...post, commentCount: Math.max(0, post.commentCount - 1) }); startTransition(async () => { const result = await deleteCommunityCommentAction(comment.id); if (!result.ok) { setComments(previous); onChange(post); onMessage(result.message); } }); }
  function confirmAction() { const current = dialog; setDialog(null); if (!current) return; startTransition(async () => { if (current === "edit") { const result = await updateCommunityPostAction(post.id, editBody); onMessage(result.message); if (result.ok) onChange({ ...post, body: editBody.trim() }); } else if (current === "delete") { const result = await deleteCommunityPostAction(post.id); onMessage(result.message); if (result.ok) onRemove(post.id); } else if (current === "hide") { const result = await moderateCommunityContentAction({ postId: post.id, hidden: true }); onMessage(result.message); if (result.ok) onRemove(post.id); } else { const result = await reportCommunityContentAction({ postId: post.id, reasonCode: "OTHER" }); onMessage(result.message); } }); }
  return <article className="community-post"><header><Avatar name={post.author.name} imageUrl={post.author.imageUrl} size="small" /><div><strong>{post.author.name}</strong><span>{post.author.productRole === "TRAINER" ? "Personal Trainer" : "Aluno"} · {relativeDate(post.publishedAt)}</span><Link href={groupBase}><i>{post.group.name}</i></Link></div>{post.pinnedAt ? <span className="community-pinned"><Pin aria-hidden="true" />Fixado</span> : null}<div className="community-post-menu"><button type="button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Ações da publicação"><MoreHorizontal aria-hidden="true" /></button>{menuOpen ? <div>{post.canEdit ? <button type="button" onClick={() => { setMenuOpen(false); setDialog("edit"); }}>Editar</button> : null}{post.canEdit || post.canModerate ? <button type="button" onClick={() => { setMenuOpen(false); setDialog(post.canEdit ? "delete" : "hide"); }}><Trash2 aria-hidden="true" />{post.canEdit ? "Excluir" : "Ocultar"}</button> : null}{post.canModerate && post.postType === "TRAINER_ANNOUNCEMENT" ? <button type="button" onClick={() => { setMenuOpen(false); startTransition(async () => { const result = await pinCommunityPostAction(post.id, !post.pinnedAt); onMessage(result.message); if (result.ok) onChange({ ...post, pinnedAt: post.pinnedAt ? null : new Date().toISOString() }); }); }}><Pin aria-hidden="true" />{post.pinnedAt ? "Desafixar" : "Fixar"}</button> : null}{!post.canEdit ? <button type="button" onClick={() => { setMenuOpen(false); setDialog("report"); }}><Flag aria-hidden="true" />Denunciar</button> : null}</div> : null}</div></header>
    {post.postType === "TRAINER_ANNOUNCEMENT" ? <span className="community-post-type"><Bell aria-hidden="true" />Aviso do Personal</span> : null}{post.body ? <p className="community-post-body">{post.body}</p> : null}
    {post.media.length ? <div className={`community-media community-media--${Math.min(post.media.length, 4)}`}>{post.media.map((media, index) => media.signedUrl ? <Image key={media.id} src={media.signedUrl} alt={`Imagem ${index + 1} da publicação de ${post.author.name}`} width={media.width || 720} height={media.height || 720} sizes="(max-width: 767px) 100vw, 680px" loading={index ? "lazy" : undefined} unoptimized /> : null)}</div> : null}
    {post.workout ? <section className="community-workout"><div><Dumbbell aria-hidden="true" /><span><small>Treino concluído</small><strong>{post.workout.sessionName}</strong></span></div><dl><div><Clock3 aria-hidden="true" /><dd>{Math.max(1, Math.round(post.workout.durationSeconds / 60))} min</dd></div><div><Check aria-hidden="true" /><dd>{post.workout.completedExercises} exercícios · {post.workout.completedSets} séries</dd></div></dl>{post.workout.canOpenDetail ? <Link href={audience === "trainer" ? "/dashboard/students" : "/student/workouts"}>Ver treino<ChevronRight aria-hidden="true" /></Link> : null}</section> : null}
    <footer className="community-post-actions"><button type="button" className={post.likedByMe ? "is-active" : undefined} onClick={like} aria-pressed={post.likedByMe}><Heart aria-hidden="true" fill={post.likedByMe ? "currentColor" : "none"}/><span>{post.likeCount || "Curtir"}</span></button><button type="button" onClick={() => commentsOpen ? setCommentsOpen(false) : void showAllComments()}><MessageCircle aria-hidden="true" /><span>{post.commentCount || "Comentar"}</span></button></footer>
    {(commentsOpen || comments.length > 0) ? <section className="community-comments" aria-label="Comentários">{!commentsOpen && post.commentCount > comments.length ? <button type="button" className="community-all-comments" onClick={() => void showAllComments()}>Ver todos os {post.commentCount} comentários</button> : null}{comments.map((comment) => <article key={comment.id} className={comment.optimistic ? "is-pending" : undefined}><Avatar name={comment.authorName} imageUrl={comment.authorImageUrl} size="small" /><div><strong>{comment.authorName}</strong><p>{comment.body}</p><small>{comment.optimistic ? "Enviando…" : relativeDate(comment.createdAt)}</small></div>{comment.canDelete ? <button type="button" aria-label="Excluir comentário" onClick={() => setConfirmComment(comment)} disabled={comment.optimistic}><Trash2 aria-hidden="true" /></button> : comment.canModerate ? <button type="button" aria-label="Ocultar comentário" onClick={() => startTransition(async () => { const result = await moderateCommunityContentAction({ commentId: comment.id, hidden: true }); onMessage(result.message); if (result.ok) setComments((current) => current.filter((item) => item.id !== comment.id)); })}><X aria-hidden="true" /></button> : null}</article>)}<form onSubmit={(event) => { event.preventDefault(); addComment(); }}><label className="sr-only" htmlFor={`comment-${post.id}`}>Adicionar comentário</label><input id={`comment-${post.id}`} value={commentBody} onChange={(event) => setCommentBody(event.target.value)} maxLength={1000} placeholder="Escreva um comentário"/><button type="submit" disabled={pending || !commentBody.trim()} aria-label="Publicar comentário"><Send aria-hidden="true" /></button></form></section> : null}
    {confirmComment ? <div className="community-dialog-layer" role="presentation"><section role="alertdialog" aria-modal="true" aria-labelledby={`delete-comment-${confirmComment.id}`}><h2 id={`delete-comment-${confirmComment.id}`}>Excluir este comentário?</h2><p>O comentário deixará de aparecer para os membros do grupo.</p><div><button type="button" onClick={() => setConfirmComment(null)}>Cancelar</button><button type="button" className="community-danger-action" onClick={() => removeComment(confirmComment)}>Excluir comentário</button></div></section></div> : null}
    {dialog ? <div className="community-dialog-layer" role="presentation"><section role="alertdialog" aria-modal="true" aria-labelledby={`dialog-${post.id}`}><h2 id={`dialog-${post.id}`}>{dialog === "edit" ? "Editar publicação" : dialog === "delete" ? "Excluir publicação?" : dialog === "hide" ? "Ocultar publicação?" : "Denunciar publicação?"}</h2>{dialog === "edit" ? <textarea value={editBody} onChange={(event) => setEditBody(event.target.value)} maxLength={2000} rows={5}/> : <p>{dialog === "delete" ? "Ela deixará de aparecer no feed. O histórico mínimo será preservado." : dialog === "hide" ? "Membros não verão mais este conteúdo." : "A moderação do grupo receberá esta denúncia."}</p>}<div><button type="button" onClick={() => setDialog(null)}>Cancelar</button><button type="button" onClick={confirmAction}>{dialog === "edit" ? "Salvar" : "Confirmar"}</button></div></section></div> : null}
  </article>;
}

function CommunityState({ icon, title, body, action }: { icon: React.ReactNode; title: string; body: string; action?: React.ReactNode }) { return <section className="community-state"><span>{icon}</span><h2>{title}</h2><p>{body}</p>{action}</section>; }
function notificationText(type: string) { const labels: Record<string, string> = { GROUP_INVITE: "Convite para grupo", JOIN_REQUEST: "Nova solicitação de entrada", JOIN_REQUEST_APPROVED: "Entrada aprovada", JOIN_REQUEST_REJECTED: "Solicitação recusada", COMMENT_ON_MY_POST: "Novo comentário", REACTION_ON_MY_POST: "Nova curtida", PINNED_ANNOUNCEMENT: "Novo aviso fixado", CHALLENGE_CREATED: "Novo desafio", CHALLENGE_ACCEPTED: "Desafio aceito" }; return labels[type] ?? "Atualização da Comunidade"; }
