"use client";

import { Bell, Camera, Check, ChevronRight, Clock3, Dumbbell, Flag, Heart, ImagePlus, MessageCircle, MoreHorizontal, Pin, Plus, Send, Trash2, X } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useRef, useState, useTransition } from "react";
import { createCommunityCommentAction, createCommunityPostAction, deleteCommunityCommentAction, deleteCommunityPostAction, moderateCommunityContentAction, pinCommunityPostAction, reportCommunityContentAction, setCommunityLikeAction, updateCommunityPostAction } from "@/app/actions/community";
import type { CommunityFilter, CommunityPost, CommunityWorkspace } from "@/lib/domain/community";
import { Avatar } from "@/components/ui/PPerfilPrimitives";

const filters: Array<{ id: CommunityFilter; label: string }> = [{ id: "ALL", label: "Todos" }, { id: "WORKOUTS", label: "Treinos" }, { id: "ANNOUNCEMENTS", label: "Avisos" }];
function dateLabel(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "Agora" : new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(date); }
function roleLabel(post: CommunityPost) { return post.author.role === "TRAINER" ? "Personal Trainer" : post.postType === "WORKOUT_COMPLETION" ? "Treino concluído" : "Aluno"; }

export function CommunityFeed({ workspace, audience, focusPostId, shareWorkoutExecutionId, studentPhotosEnabled = false }: { workspace: CommunityWorkspace; audience: "trainer" | "student"; focusPostId?: string; shareWorkoutExecutionId?: string; studentPhotosEnabled?: boolean }) {
  const router = useRouter(), dialog = useRef<HTMLDialogElement>(null);
  const [pending, startTransition] = useTransition(), [message, setMessage] = useState<string | null>(null), [composerType, setComposerType] = useState<"TEXT" | "TRAINER_ANNOUNCEMENT" | "WORKOUT_COMPLETION" | "PHOTO">(shareWorkoutExecutionId ? "WORKOUT_COMPLETION" : "TEXT"), [draft, setDraft] = useState(""), [files, setFiles] = useState<File[]>([]);
  const community = workspace.activeCommunity;
  const posts = focusPostId ? workspace.posts.filter((post) => post.id === focusPostId) : workspace.posts;
  const base = audience === "trainer" ? "/dashboard/community" : "/student/community";
  const olderPostsHref = workspace.nextCursor ? `${base}?${new URLSearchParams({ ...(workspace.filter !== "ALL" ? { filter: workspace.filter } : {}), ...(workspace.communities.length > 1 ? { community: community?.id ?? "" } : {}), beforeAt: workspace.nextCursor.createdAt, beforeId: workspace.nextCursor.id }).toString()}` : null;
  const photosAllowed = audience === "trainer" || studentPhotosEnabled;
  function run(operation: () => Promise<{ ok: boolean; message: string }>) { startTransition(async () => { const result = await operation(); setMessage(result.message); if (result.ok) router.refresh(); }); }
  function closeComposer() { if (draft.trim() || files.length) { if (!window.confirm("Descartar esta publicação?")) return; } dialog.current?.close(); setDraft(""); setFiles([]); }
  async function publish() {
    if (!community) return;
    if (composerType === "PHOTO") {
      const form = new FormData(); form.set("communityId", community.id); form.set("body", draft); files.forEach((file) => form.append("images", file));
      startTransition(async () => { const response = await fetch("/api/community/photos", { method: "POST", body: form }); const result = await response.json() as { ok: boolean; message: string }; setMessage(result.message); if (result.ok) { dialog.current?.close(); setDraft(""); setFiles([]); router.refresh(); } }); return;
    }
    startTransition(async () => { const result = await createCommunityPostAction({ communityId: community.id, type: composerType, body: draft, workoutExecutionId: composerType === "WORKOUT_COMPLETION" ? shareWorkoutExecutionId : undefined }); setMessage(result.message); if (result.ok) { dialog.current?.close(); setDraft(""); router.replace(base); router.refresh(); } });
  }
  if (!community) return <section className="community-unavailable"><span>Comunidade</span><h1>{workspace.unavailableReason === "ENTITLEMENT" ? "Comunidade indisponível no seu acesso atual" : "Nenhuma Comunidade disponível"}</h1><p>{audience === "trainer" ? "Seus dados permanecem preservados e reaparecem quando o acesso for reativado." : "Você precisa de um acompanhamento ativo para entrar no clube do seu Personal."}</p></section>;
  return <div className={`community-page community-page--${audience}`}>
    <header className="community-header"><div><span>Comunidade privada</span><h1>{community.name}</h1><p>{audience === "trainer" ? "Seu clube. Seus alunos. Um espaço de constância." : `Com ${community.trainerName} e seus alunos.`}</p></div>{!focusPostId ? <button type="button" className="community-compose-trigger" onClick={() => dialog.current?.showModal()}><Plus aria-hidden="true" /><span>Publicar</span></button> : <Link href={base}>Voltar ao feed</Link>}</header>
    {workspace.communities.length > 1 ? <nav className="community-switcher" aria-label="Suas comunidades">{workspace.communities.map((item) => <Link key={item.id} href={`${base}?community=${item.id}`} aria-current={item.id === community.id ? "page" : undefined}>{item.name}</Link>)}</nav> : null}
    {!focusPostId ? <nav className="community-filters" aria-label="Filtrar publicações">{filters.map((item) => <Link key={item.id} href={`${base}?filter=${item.id}`} aria-current={workspace.filter === item.id ? "page" : undefined}>{item.label}</Link>)}</nav> : null}
    {message ? <p className="community-feedback" role="status">{message}</p> : null}
    <section className="community-feed" aria-label="Publicações">
      {posts.length ? posts.map((post) => <article className="community-post" key={post.id}>
        <header><Avatar name={post.author.name} imageUrl={post.author.imageUrl} size="small" /><div><strong>{post.author.name}</strong><span>{roleLabel(post)} · {dateLabel(post.createdAt)}</span></div>{post.pinnedAt ? <span className="community-pinned"><Pin aria-hidden="true" />Fixado</span> : null}<details className="community-post-menu"><summary aria-label="Ações da publicação"><MoreHorizontal aria-hidden="true" /></summary><div>
          {post.canEdit ? <button onClick={() => { const body = window.prompt("Editar publicação", post.body ?? ""); if (body && body !== post.body) run(() => updateCommunityPostAction(post.id, body)); }}>Editar</button> : null}
          {post.canEdit ? <button onClick={() => window.confirm("Excluir esta publicação? O histórico mínimo será preservado.") && run(() => deleteCommunityPostAction(post.id))}><Trash2 aria-hidden="true" />Excluir</button> : null}
          {post.canModerate && post.postType === "TRAINER_ANNOUNCEMENT" ? <button onClick={() => run(() => pinCommunityPostAction(post.id, !post.pinnedAt))}><Pin aria-hidden="true" />{post.pinnedAt ? "Desafixar" : "Fixar"}</button> : null}
          {post.canModerate && !post.canEdit ? <button onClick={() => window.confirm("Ocultar esta publicação do grupo?") && run(() => moderateCommunityContentAction({ postId: post.id, hidden: true }))}>Ocultar</button> : null}
          {!post.canEdit ? <button onClick={() => run(() => reportCommunityContentAction({ postId: post.id, reasonCode: "OTHER" }))}><Flag aria-hidden="true" />Denunciar</button> : null}
        </div></details></header>
        {post.postType === "TRAINER_ANNOUNCEMENT" ? <span className="community-post-type"><Bell aria-hidden="true" />Aviso do Personal</span> : null}
        {post.body ? <p className="community-post-body">{post.body}</p> : null}
        {post.media.length ? <div className={`community-media community-media--${Math.min(post.media.length, 4)}`}>{post.media.map((media) => media.signedUrl ? <Image key={media.id} src={media.signedUrl} alt="Imagem da publicação" width={720} height={720} unoptimized /> : null)}</div> : null}
        {post.workout ? <section className="community-workout"><div><Dumbbell aria-hidden="true" /><span><small>Treino concluído</small><strong>{post.workout.sessionName}</strong></span></div><dl><div><Clock3 aria-hidden="true" /><dd>{Math.max(1, Math.round(post.workout.durationSeconds / 60))} min</dd></div><div><Check aria-hidden="true" /><dd>{post.workout.completedExercises} exercícios · {post.workout.completedSets} séries</dd></div></dl>{post.workout.canOpenDetail ? <Link href={audience === "trainer" ? "/dashboard/students" : "/student/workouts"}>Ver detalhes autorizados<ChevronRight aria-hidden="true" /></Link> : null}</section> : null}
        <footer className="community-post-actions"><button type="button" className={post.likedByMe ? "is-active" : undefined} onClick={() => run(() => setCommunityLikeAction(post.id, !post.likedByMe))} disabled={pending}><Heart aria-hidden="true" fill={post.likedByMe ? "currentColor" : "none"} /><span>{post.likeCount || "Curtir"}</span></button><Link href={`${base}/posts/${post.id}`}><MessageCircle aria-hidden="true" /><span>{post.comments.length || "Comentar"}</span></Link></footer>
        {(focusPostId || post.comments.length > 0) ? <section className="community-comments" aria-label="Comentários">{post.comments.map((comment) => <article key={comment.id}><Avatar name={comment.authorName} imageUrl={comment.authorImageUrl} size="small" /><div><strong>{comment.authorName}</strong><p>{comment.body}</p><small>{dateLabel(comment.createdAt)}</small></div>{comment.canDelete ? <button aria-label="Excluir comentário" onClick={() => window.confirm("Excluir este comentário?") && run(() => deleteCommunityCommentAction(comment.id))}><Trash2 aria-hidden="true" /></button> : comment.canModerate ? <button aria-label="Ocultar comentário" onClick={() => window.confirm("Ocultar este comentário do grupo?") && run(() => moderateCommunityContentAction({ commentId: comment.id, hidden: true }))}><X aria-hidden="true" /></button> : <button aria-label="Denunciar comentário" onClick={() => run(() => reportCommunityContentAction({ commentId: comment.id, reasonCode: "OTHER" }))}><Flag aria-hidden="true" /></button>}</article>)}<CommentForm postId={post.id} pending={pending} onSubmit={(body) => run(() => createCommunityCommentAction(post.id, body))} /></section> : null}
      </article>) : <div className="community-empty"><span>{audience === "trainer" ? <Bell aria-hidden="true" /> : <Dumbbell aria-hidden="true" />}</span><h2>{audience === "trainer" ? "Comece publicando um aviso para seus alunos." : "Os treinos, avisos e conquistas do seu grupo aparecerão aqui."}</h2>{audience === "trainer" ? <button onClick={() => { setComposerType("TRAINER_ANNOUNCEMENT"); dialog.current?.showModal(); }}>Publicar aviso</button> : null}</div>}
    </section>
    {olderPostsHref ? <Link className="community-load-more" href={olderPostsHref}>Publicações mais antigas</Link> : null}
    <dialog ref={dialog} className="community-composer" open={shareWorkoutExecutionId ? true : undefined} onCancel={(event) => { event.preventDefault(); closeComposer(); }}><section><header><button type="button" onClick={closeComposer} aria-label="Fechar"><X aria-hidden="true" /></button><div><span>Nova publicação</span><strong>{community.name}</strong></div><button type="button" onClick={publish} disabled={pending || (composerType === "PHOTO" ? files.length === 0 : composerType !== "WORKOUT_COMPLETION" && draft.trim().length === 0)}>{pending ? "Publicando…" : "Publicar"}</button></header><nav aria-label="Tipo de publicação"><button className={composerType === "TEXT" ? "active" : undefined} onClick={() => setComposerType("TEXT")}><MessageCircle aria-hidden="true" />Publicação</button>{shareWorkoutExecutionId ? <button className={composerType === "WORKOUT_COMPLETION" ? "active" : undefined} onClick={() => setComposerType("WORKOUT_COMPLETION")}><Dumbbell aria-hidden="true" />Treino concluído</button> : null}{photosAllowed ? <button className={composerType === "PHOTO" ? "active" : undefined} onClick={() => setComposerType("PHOTO")}><Camera aria-hidden="true" />Fotos</button> : null}{audience === "trainer" ? <button className={composerType === "TRAINER_ANNOUNCEMENT" ? "active" : undefined} onClick={() => setComposerType("TRAINER_ANNOUNCEMENT")}><Bell aria-hidden="true" />Aviso</button> : null}</nav>{composerType === "WORKOUT_COMPLETION" ? <div className="community-workout-preview"><Dumbbell aria-hidden="true" /><div><small>Publicação privada</small><strong>Seu treino concluído</strong><p>Somente duração, exercícios e séries concluídas serão exibidos.</p></div></div> : null}<label htmlFor="community-body">{composerType === "TRAINER_ANNOUNCEMENT" ? "O que seus alunos precisam saber?" : composerType === "WORKOUT_COMPLETION" ? "Legenda opcional" : "Compartilhe com seu grupo"}</label><textarea id="community-body" value={draft} onChange={(event) => setDraft(event.target.value)} maxLength={2000} rows={8} placeholder={composerType === "WORKOUT_COMPLETION" ? "Como foi o treino?" : "Escreva aqui…"} /><small>{draft.length}/2000</small>{composerType === "PHOTO" ? <label className="community-file"><ImagePlus aria-hidden="true" /><span>{files.length ? `${files.length} ${files.length === 1 ? "imagem selecionada" : "imagens selecionadas"}` : "Escolher até 4 imagens"}</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(event) => setFiles(Array.from(event.target.files ?? []).slice(0, 4))} /></label> : null}</section></dialog>
  </div>;
}

function CommentForm({ postId, pending, onSubmit }: { postId: string; pending: boolean; onSubmit: (body: string) => void }) {
  const [body, setBody] = useState("");
  return <form onSubmit={(event) => { event.preventDefault(); if (body.trim()) { onSubmit(body); setBody(""); } }}><label className="sr-only" htmlFor={`comment-${postId}`}>Adicionar comentário</label><input id={`comment-${postId}`} value={body} onChange={(event) => setBody(event.target.value)} maxLength={1000} placeholder="Escreva um comentário" /><button type="submit" disabled={pending || !body.trim()} aria-label="Publicar comentário"><Send aria-hidden="true" /></button></form>;
}
