import "server-only";
import type { CreatedInvitation, ManagedInvitation, ManagedStudent } from "@/lib/domain/students";
import { createDemoInvitation, getDemoInvitations, getDemoStudents } from "@/lib/demo/product-workspace";
import { isDemoWorkspaceRequest } from "@/lib/demo/workspace";
import { createClient } from "@/lib/supabase/server";

type StudentRpc={id:string;student_profile_id:string;name:string;email:string|null;status:ManagedStudent["status"];origin:ManagedStudent["origin"];started_at:string;inactive_at:string|null;ended_at:string|null};
type InvitationRpc={id:string;name:string|null;email:string;status:ManagedInvitation["status"];expires_at:string;created_at:string};
const mapStudent=(x:StudentRpc):ManagedStudent=>({id:x.id,studentProfileId:x.student_profile_id,name:x.name,email:x.email,status:x.status,origin:x.origin,startedAt:x.started_at,inactiveAt:x.inactive_at,endedAt:x.ended_at});
export async function getStudentsWorkspace(){if(await isDemoWorkspaceRequest())return{students:getDemoStudents(),invitations:getDemoInvitations()};const supabase=await createClient();const{data,error}=await supabase.rpc("get_my_students");if(error||!data)throw new Error("Unable to load students.");const value=data as {relationships:StudentRpc[];invitations:InvitationRpc[]};return{students:(value.relationships??[]).map(mapStudent),invitations:(value.invitations??[]).map(x=>({id:x.id,name:x.name,email:x.email,status:x.status,expiresAt:x.expires_at,createdAt:x.created_at}))}}
export async function getStudentDetail(id:string){if(await isDemoWorkspaceRequest())return getDemoStudents().find(student=>student.id===id)??null;const supabase=await createClient();const{data,error}=await supabase.rpc("get_my_student_detail",{p_relationship_id:id});if(error)throw new Error("Unable to load student.");return data?mapStudent(data as StudentRpc):null}
export async function createNamedInvitation(name:string,email:string){if(await isDemoWorkspaceRequest()){const created=createDemoInvitation(name,email);return{invitationId:created.invitation.id,token:created.token,expiresAt:created.invitation.expiresAt} satisfies CreatedInvitation}const supabase=await createClient();const{data,error}=await supabase.rpc("create_named_student_invitation",{p_name:name,p_email:email});if(error||!data)throw error??new Error("Invitation failed");const x=data as {invitation_id:string;token:string;expires_at:string};return{invitationId:x.invitation_id,token:x.token,expiresAt:x.expires_at} satisfies CreatedInvitation}
export async function deactivateStudent(id:string){if(await isDemoWorkspaceRequest())throw new Error("demo_workspace_read_only");const supabase=await createClient();const{error}=await supabase.rpc("deactivate_my_trainer_student_relationship",{p_relationship_id:id});if(error)throw error}
export async function acceptStudentInvitation(token:string,name?:string){if(await isDemoWorkspaceRequest())throw new Error("demo_workspace_read_only");const supabase=await createClient();const{data,error}=await supabase.rpc("accept_student_invitation",{p_token:token,p_preferred_name:name||null});if(error||typeof data!=="string")throw error??new Error("Invitation invalid");return data}
