"use client";
import Link from "next/link"; import { ArrowLeft,ArrowRight,Check,MapPin } from "lucide-react"; import { useActionState,useState } from "react";
import { createLead,type LeadActionState } from "@/app/actions/leads"; import { PersonAvatar } from "@/components/ui/PersonAvatar"; import { leadsConfig } from "@/config/site";
const initial:LeadActionState={}; const modes=[{value:"online",label:"Online"},{value:"presencial",label:"Presencial"},{value:"both",label:"Tanto faz"}];
export function LeadQuiz(){const[started,setStarted]=useState(false),[step,setStep]=useState(0),[mode,setMode]=useState(""),[state,action,pending]=useActionState(createLead,initial);const total=6;
function begin(){setStarted(true);void fetch("/api/analytics",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event:"lead_form_started"})})}
if(state.ok)return <section className="lead-results"><div className="leads-brand">Cheipi</div><h1>Encontramos profissionais compatíveis com você 🎯</h1><p>Compatibilidade calculada pelas preferências que você informou.</p>{state.matches?.length?<div className="match-list">{state.matches.map(m=><article key={m.slug} className="match-card"><PersonAvatar name={m.name} src={m.photo_url} size="large" className="match-avatar" /><div><strong>{m.name}</strong><span>{m.specialty}</span>{m.city?<small><MapPin/> {m.city}</small>:null}</div><b>{m.score}%<small> compatível</small></b><Link href={`/p/${m.slug}`}>Ver perfil <ArrowRight/></Link></article>)}</div>:<div className="no-match"><h2>Ainda estamos ampliando a rede.</h2><p>Seu pedido foi registrado, mas nenhum profissional disponível atingiu os critérios agora.</p></div>}<Link className="quiz-secondary" href="/">Voltar à Cheipi</Link></section>;
if(!started)return <section className="quiz-intro"><div className="leads-brand">P<span>Perfil</span></div><div><h1>Encontre o Personal certo para o seu objetivo.</h1><p>Conte rapidamente o que você procura e encontraremos profissionais compatíveis com seu objetivo, rotina e investimento.</p><button onClick={begin}>Encontrar meu Personal <ArrowRight/></button><small><Check/> Sem cadastro. Leva menos de 2 minutos.</small></div></section>;
return <form action={action} className="lead-quiz"><header><button type="button" aria-label="Voltar" onClick={()=>step?setStep(step-1):setStarted(false)}><ArrowLeft/></button><div className="leads-brand">P<span>Perfil</span></div><span>{step+1} de {total}</span></header><div className="quiz-progress"><i style={{width:`${((step+1)/total)*100}%`}}/></div>
<div className="quiz-stage" hidden={step!==0}><h1>Qual é o seu principal objetivo?</h1><div className="quiz-options">{leadsConfig.goals.map(x=><label key={x.value}><input type="radio" name="goal" value={x.value} required onChange={()=>setStep(1)}/><span>{x.label}</span></label>)}</div></div>
<div className="quiz-stage" hidden={step!==1}><h1>Como você prefere treinar?</h1><div className="quiz-options">{modes.map(x=><label key={x.value}><input type="radio" name="service_mode" value={x.value} required onChange={()=>{setMode(x.value);setStep(x.value==="online"?3:2)}}/><span>{x.label}</span></label>)}</div></div>
<div className="quiz-stage" hidden={step!==2}><h1>Em qual cidade você procura atendimento?</h1><div className="quiz-location"><label>Cidade<input name="city" maxLength={120} required={mode!=="online"}/></label><label>Estado<input name="state" maxLength={2} required={mode!=="online"} placeholder="SP"/></label></div><button type="button" className="quiz-next" onClick={()=>setStep(3)}>Continuar <ArrowRight/></button></div>
<div className="quiz-stage" hidden={step!==3}><h1>Quanto pretende investir no acompanhamento?</h1><div className="quiz-options">{leadsConfig.budgetBands.map(x=><label key={x.value}><input type="radio" name="budget_band" value={x.value} required onChange={()=>setStep(4)}/><span>{x.label}</span></label>)}</div></div>
<div className="quiz-stage" hidden={step!==4}><h1>Quando você pretende começar?</h1><div className="quiz-options">{leadsConfig.timings.map(x=><label key={x.value}><input type="radio" name="start_timing" value={x.value} required onChange={()=>setStep(5)}/><span>{x.label}</span></label>)}</div></div>
<div className="quiz-stage contact-stage" hidden={step!==5}><p>Último passo</p><h1>Encontramos profissionais que podem combinar com você.</h1><label>Primeiro nome<input name="first_name" minLength={2} maxLength={60} required/></label><label>WhatsApp<input name="whatsapp" inputMode="tel" maxLength={20} required/></label><label>E-mail <small>opcional</small><input name="email" type="email" maxLength={254}/></label><input className="honey" name="company" tabIndex={-1} autoComplete="off"/><label className="consent"><input type="checkbox" name="consent" required/><span>Concordo que meus dados sejam usados pela Cheipi para encontrar e permitir o contato de profissionais compatíveis.</span></label>{state.message?<p className="quiz-error" role="alert">{state.message}</p>:null}<button className="quiz-next" disabled={pending}>{pending?"Buscando profissionais...":"Ver meus resultados"} <ArrowRight/></button></div></form>}
