"use client";

import { ArrowLeft, Check, Copy, ExternalLink, LoaderCircle, Share2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useActionState, useEffect, useRef, useState } from "react";
import { requestOnboardingPublication, saveOnboardingIdentity, saveOnboardingProfessional, saveOnboardingSocial, saveOnboardingTemplate, type OnboardingActionState } from "@/app/actions/onboarding";
import { InviteStudentForm } from "@/components/students/InviteStudentForm";
import { templateCatalog } from "@/lib/domain/template-registry";
import type { TrainerProfile } from "@/lib/domain/trainer";

export type OnboardingDraft={display_name?:string|null;professional_name?:string|null;profile_image_url?:string|null;specialty_code?:string|null;specialty_label?:string|null;service_mode?:string|null;city?:string|null;cref?:string|null;whatsapp?:string|null;instagram?:string|null;tiktok?:string|null;youtube?:string|null;template_id?:string|null;identity_completed_at?:string|null;professional_completed_at?:string|null;social_completed_at?:string|null;template_completed_at?:string|null};
type Props={draft:OnboardingDraft|null;profile:TrainerProfile|null;billing:{billing_state?:string;product_code?:string}|null;canPublish:boolean;hasStudentActivity:boolean;publicUrl:string|null;checkoutReturned:boolean};
type OnboardingStage="identity"|"professional"|"social"|"template"|"ready"|"trial"|"syncing"|"published";
type EditableStage=Extract<OnboardingStage,"identity"|"professional"|"social"|"template"|"ready">;
const initial:OnboardingActionState={};

function BackButton({onClick}:{onClick:()=>void}){return <button type="button" className="pc-onboarding-back" onClick={onClick}><ArrowLeft aria-hidden="true"/>Voltar</button>}

function SubmitForm({action,children,submit,onBack,multipart=false}:{action:(state:OnboardingActionState,data:FormData)=>Promise<OnboardingActionState>;children:React.ReactNode;submit:string;onBack?:()=>void;multipart?:boolean}){const[state,formAction,pending]=useActionState(action,initial);return <form action={formAction} encType={multipart?"multipart/form-data":undefined} className="pc-onboarding-step">{children}{state.message?<p className="form-message" role="status">{state.message}</p>:null}<div className="pc-onboarding-actions">{onBack?<BackButton onClick={onBack}/>:null}<button className="pc-onboarding-primary" disabled={pending}>{pending?"Salvando…":submit}</button></div></form>}

function ProfessionalForm({draft,onBack,initialPhase="specialty"}:{draft:OnboardingDraft|null;onBack:()=>void;initialPhase?:"specialty"|"service"}){const[state,formAction,pending]=useActionState(saveOnboardingProfessional,initial);const[phase,setPhase]=useState<"specialty"|"service">(initialPhase);const[custom,setCustom]=useState(draft?.specialty_code==="custom");const formRef=useRef<HTMLFormElement>(null);function continueToService(){if(formRef.current?.reportValidity())setPhase("service")}return <form ref={formRef} action={formAction} className="pc-onboarding-step">
  <section hidden={phase!=="specialty"} className="pc-onboarding-substep"><header><span>Seu trabalho</span><h1>Qual é sua especialidade?</h1><p>Escolha a área que melhor representa seu trabalho hoje.</p></header><label>Especialidade principal<select name="specialty_code" defaultValue={draft?.specialty_code??"hypertrophy"} onChange={e=>setCustom(e.target.value==="custom")}><option value="hypertrophy">Hipertrofia</option><option value="weight_loss">Emagrecimento</option><option value="strength">Força</option><option value="conditioning">Condicionamento</option><option value="running">Corrida</option><option value="mobility">Mobilidade</option><option value="custom">Outra especialidade</option></select></label>{custom?<label>Qual especialidade? *<input name="custom_specialty" defaultValue={draft?.specialty_label??""} required minLength={2} maxLength={120}/></label>:null}</section>
  <section hidden={phase!=="service"} className="pc-onboarding-substep"><header><span>Seu atendimento</span><h1>Como você atende seus alunos?</h1></header><fieldset className="pc-mode-fieldset"><legend>Formato de atendimento</legend><div>{[["online","Online"],["presencial","Presencial"],["both","Híbrido"]].map(([value,label])=><label key={value}><input type="radio" name="service_mode" value={value} defaultChecked={(draft?.service_mode??"both")===value} required/><span>{label}</span></label>)}</div></fieldset><label>Cidade <input name="city" defaultValue={draft?.city??""} maxLength={120} autoComplete="address-level2"/></label><label>CREF <input name="cref" defaultValue={draft?.cref??""} maxLength={60}/></label></section>
  {state.message?<p className="form-message" role="status">{state.message}</p>:null}<div className="pc-onboarding-actions">{phase==="specialty"?<BackButton onClick={onBack}/>:<BackButton onClick={()=>setPhase("specialty")}/>} {phase==="specialty"?<button type="button" className="pc-onboarding-primary" onClick={continueToService}>Continuar</button>:<button className="pc-onboarding-primary" disabled={pending}>{pending?"Salvando…":"Continuar"}</button>}</div>
</form>}

function CheckoutButton({onConfirmationPending}:{onConfirmationPending:()=>void}){const[pending,setPending]=useState(false);const[message,setMessage]=useState("");async function start(){setPending(true);setMessage("");try{const response=await fetch("/api/billing/stripe/checkout?flow=onboarding",{method:"POST",headers:{"content-type":"application/json"},body:"{}"});const data=await response.json() as {checkoutUrl?:string;message?:string;code?:string};if(response.status===409&&(data.code==="ALREADY_SUBSCRIBED"||data.code==="CHECKOUT_CONFIRMATION_PENDING")){onConfirmationPending();return}if(!response.ok||!data.checkoutUrl)throw new Error(data.message||"Não foi possível abrir o Checkout.");window.location.assign(data.checkoutUrl)}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível abrir o Checkout.");setPending(false)}}return <><button type="button" className="pc-onboarding-primary" disabled={pending} onClick={start}>{pending?"Abrindo Checkout…":"Ativar 7 dias grátis"}</button>{message?<p role="status" className="form-message">{message}</p>:null}</>}

const POLL_INTERVAL_MS=3000;
const MAX_POLL_ATTEMPTS=8;
function ActivationConfirmation(){const router=useRouter();const[timedOut,setTimedOut]=useState(false);const[cycle,setCycle]=useState(0);const attempts=useRef(0);useEffect(()=>{attempts.current=0;let timer:number|undefined;let stopped=false;function poll(){if(stopped)return;if(attempts.current>=MAX_POLL_ATTEMPTS){setTimedOut(true);return}attempts.current+=1;router.refresh();timer=window.setTimeout(poll,POLL_INTERVAL_MS)}timer=window.setTimeout(poll,1200);return()=>{stopped=true;if(timer)window.clearTimeout(timer)}},[cycle,router]);function retry(){setTimedOut(false);setCycle(value=>value+1)}return <section className="pc-onboarding-step pc-onboarding-processing" aria-live="polite"><LoaderCircle aria-hidden="true"/><header><span>Confirmação segura</span><h1>{timedOut?"A ativação ainda está sendo confirmada":"Estamos confirmando sua assinatura…"}</h1><p>{timedOut?"Seu pagamento foi recebido, mas ainda estamos confirmando a ativação.":"Isso normalmente leva alguns segundos."}</p></header>{timedOut?<div className="pc-onboarding-actions"><a className="pc-onboarding-secondary" href="/dashboard">Continuar depois</a><button type="button" className="pc-onboarding-primary" onClick={retry}>Verificar novamente</button></div>:<p className="pc-processing-note">Você pode manter esta página aberta. Ela avançará automaticamente após a confirmação.</p>}</section>}

function stageOf(draft:OnboardingDraft|null,profile:TrainerProfile|null,canPublish:boolean):OnboardingStage{if(profile){if(!profile.publication_requested_at)return"ready";if(!canPublish)return"trial";if(!profile.published)return"syncing";return"published"}if(!draft?.identity_completed_at)return"identity";if(!draft.professional_completed_at)return"professional";if(!draft.social_completed_at)return"social";return"template"}

export function OnboardingForm({draft,profile,billing,canPublish,hasStudentActivity,publicUrl,checkoutReturned}:Props){const authoritativeStage=stageOf(draft,profile,canPublish);const[editingStage,setEditingStage]=useState<EditableStage|null>(null);const[checkoutPending,setCheckoutPending]=useState(false);const stage=editingStage??authoritativeStage;const[publishState,publishAction,publishPending]=useActionState(requestOnboardingPublication,initial);const activeBilling=billing?.billing_state==="ACTIVE"||billing?.billing_state==="GRACE";const confirming=authoritativeStage==="syncing"||(authoritativeStage==="trial"&&(checkoutReturned||checkoutPending||activeBilling));
  if(confirming)return <div className="pc-onboarding-form" data-stage="syncing"><ActivationConfirmation/></div>;
  return <div className="pc-onboarding-form" data-stage={stage}>
    <div className="pc-onboarding-progress" aria-label="Progresso"><span data-complete><i><Check/></i><small>Conta</small></span><span data-active><i>2</i><small>Seu site</small></span><span data-complete={stage==="published"||undefined}><i>3</i><small>Publicar</small></span><span><i>4</i><small>Primeiro aluno</small></span></div>
    {stage==="identity"?<SubmitForm action={saveOnboardingIdentity} submit="Continuar" multipart><header><span>Seu site começa por você</span><h1>Sua identidade profissional</h1><p>Use uma foto nítida e o nome que seus alunos reconhecem.</p></header><label className="pc-photo-input">Foto profissional<input name="image" type="file" accept="image/jpeg,image/png,image/webp"/><small>JPG, PNG ou WebP · até 5 MB</small></label><label>Nome *<input name="display_name" defaultValue={draft?.display_name??""} required minLength={2} maxLength={100} autoComplete="name"/></label><label>Nome profissional<input name="professional_name" defaultValue={draft?.professional_name??""} maxLength={100}/></label></SubmitForm>:null}
    {stage==="professional"?<ProfessionalForm draft={draft} initialPhase={authoritativeStage==="professional"?"specialty":"service"} onBack={()=>setEditingStage("identity")}/>:null}
    {stage==="social"?<SubmitForm action={saveOnboardingSocial} submit="Escolher estilo" onBack={()=>setEditingStage("professional")}><header><span>Contato direto</span><h1>Onde seus alunos encontram você?</h1><p>WhatsApp é necessário. Os demais canais podem ficar para depois.</p></header><label>WhatsApp *<input name="whatsapp" type="tel" inputMode="tel" autoComplete="tel" defaultValue={draft?.whatsapp??""} required placeholder="55 11 99999-9999"/></label><label>Instagram <input name="instagram" defaultValue={draft?.instagram??""} placeholder="@seuperfil" maxLength={120}/></label><label>TikTok <input name="tiktok" defaultValue={draft?.tiktok??""} placeholder="@seuperfil" maxLength={160}/></label><label>YouTube <input name="youtube" type="text" defaultValue={draft?.youtube??""} placeholder="@seucanal ou URL" maxLength={360}/></label></SubmitForm>:null}
    {stage==="template"?<SubmitForm action={saveOnboardingTemplate} submit="Gerar meu site" onBack={()=>setEditingStage("social")}><header><span>Escolha visual</span><h1>Qual estilo representa seu trabalho?</h1><p>São os mesmos templates usados no site publicado.</p></header><div className="pc-template-options">{templateCatalog.filter(t=>t.availability.production).map((template,index)=><label key={template.id} className="pc-template-choice" data-template={template.id}><input type="radio" name="template_id" value={template.id} defaultChecked={(draft?.template_id??"template_01")===template.id}/><i aria-hidden="true">{String(index+1).padStart(2,"0")}</i><strong>{template.name}</strong><small>{template.description}</small></label>)}</div></SubmitForm>:null}
    {stage==="ready"&&profile?<section className="pc-onboarding-step pc-onboarding-ready"><header><span>Primeiro momento de valor</span><h1>Seu site está pronto</h1><p>Veja o site real com seus dados antes de decidir publicar.</p></header><div className="pc-real-preview"><iframe title="Prévia real do seu site" src={`/site-preview?template=${profile.template_id}`}/></div><form action={publishAction}><button className="pc-onboarding-primary" disabled={publishPending}>{publishPending?"Preparando…":"Publicar meu site"}</button></form>{publishState.message?<p role="status" className="form-message">{publishState.message}</p>:null}<div className="pc-onboarding-actions"><a className="pc-onboarding-back" href="/dashboard/site"><ArrowLeft aria-hidden="true"/>Voltar</a><a className="pc-onboarding-secondary" href="/dashboard/site">Continuar editando</a></div></section>:null}
    {stage==="trial"?<section className="pc-onboarding-step pc-trial"><header><span>Desbloqueie a publicação</span><h1>7 dias de PPerfil PRO</h1><p>Seu site já está salvo. Ative o trial para colocá-lo no ar.</p></header><div className="pc-trial-price"><strong>R$ 0</strong><span>hoje</span></div><ul><li>Cartão necessário para iniciar</li><li>7 dias grátis</li><li>R$ 59,90/mês depois</li><li>Cancele antes do fim do trial e não pague nada</li></ul><CheckoutButton onConfirmationPending={()=>setCheckoutPending(true)}/><small>A publicação só acontece após confirmação autoritativa do Stripe. Retornar do Checkout não ativa o PRO.</small></section>:null}
    {stage==="published"&&profile&&publicUrl?<section className="pc-onboarding-step pc-published"><header><span>{activeBilling?"PRO ativo":"Publicação disponível"}</span><h1>Seu site está no ar</h1><p>Agora seus alunos já podem encontrar você.</p></header><div className="pc-public-link"><strong>{publicUrl}</strong><button type="button" onClick={()=>navigator.clipboard.writeText(publicUrl)}><Copy/>Copiar link</button></div><div className="pc-publish-actions"><a href={publicUrl} target="_blank" rel="noreferrer"><ExternalLink/>Abrir site</a><a href={`https://wa.me/?text=${encodeURIComponent(`Conheça meu site: ${publicUrl}`)}`} target="_blank" rel="noreferrer"><Share2/>Compartilhar no WhatsApp</a></div><p className="pc-honest-note">Adicione este link à sua bio do Instagram ou TikTok.</p>{hasStudentActivity?<a className="pc-onboarding-primary" href="/dashboard">Ir para o Dashboard</a>:<div className="pc-first-student"><h2>Convide seu primeiro aluno</h2><p>A entrega por e-mail ainda não está ativa. Crie o convite e compartilhe o link gerado.</p><InviteStudentForm/></div>}</section>:null}
  </div>;
}
