"use client";

import { Check, Copy, ExternalLink, Share2 } from "lucide-react";
import { useActionState, useState } from "react";
import { requestOnboardingPublication, saveOnboardingIdentity, saveOnboardingProfessional, saveOnboardingSocial, saveOnboardingTemplate, type OnboardingActionState } from "@/app/actions/onboarding";
import { InviteStudentForm } from "@/components/students/InviteStudentForm";
import { templateCatalog } from "@/lib/domain/template-registry";
import type { TrainerProfile } from "@/lib/domain/trainer";

export type OnboardingDraft={display_name?:string|null;professional_name?:string|null;profile_image_url?:string|null;specialty_code?:string|null;specialty_label?:string|null;service_mode?:string|null;city?:string|null;cref?:string|null;whatsapp?:string|null;instagram?:string|null;tiktok?:string|null;youtube?:string|null;template_id?:string|null;identity_completed_at?:string|null;professional_completed_at?:string|null;social_completed_at?:string|null;template_completed_at?:string|null};
type Props={draft:OnboardingDraft|null;profile:TrainerProfile|null;billing:{billing_state?:string;product_code?:string}|null;canPublish:boolean;hasStudentActivity:boolean;publicUrl:string|null};
const initial:OnboardingActionState={};

function SubmitForm({action,children,submit,multipart=false}:{action:(state:OnboardingActionState,data:FormData)=>Promise<OnboardingActionState>;children:React.ReactNode;submit:string;multipart?:boolean}){const[state,formAction,pending]=useActionState(action,initial);return <form action={formAction} encType={multipart?"multipart/form-data":undefined} className="pc-onboarding-step">{children}{state.message?<p className="form-message" role="status">{state.message}</p>:null}<button className="pc-onboarding-primary" disabled={pending}>{pending?"Salvando…":submit}</button></form>}

function CheckoutButton(){const[pending,setPending]=useState(false);const[message,setMessage]=useState("");async function start(){setPending(true);setMessage("");try{const response=await fetch("/api/billing/stripe/checkout?flow=onboarding",{method:"POST",headers:{"content-type":"application/json"},body:"{}"});const data=await response.json() as {checkoutUrl?:string;message?:string};if(!response.ok||!data.checkoutUrl)throw new Error(data.message||"Não foi possível abrir o Checkout.");window.location.assign(data.checkoutUrl)}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível abrir o Checkout.");setPending(false)}}return <><button type="button" className="pc-onboarding-primary" disabled={pending} onClick={start}>{pending?"Abrindo Checkout…":"Ativar 7 dias grátis"}</button>{message?<p role="status" className="form-message">{message}</p>:null}</>}

function stageOf(draft:OnboardingDraft|null,profile:TrainerProfile|null,canPublish:boolean){if(profile){if(!profile.publication_requested_at)return"ready";if(!canPublish)return"trial";if(!profile.published)return"syncing";return"published"}if(!draft?.identity_completed_at)return"identity";if(!draft.professional_completed_at)return"professional";if(!draft.social_completed_at)return"social";return"template"}

export function OnboardingForm({draft,profile,billing,canPublish,hasStudentActivity,publicUrl}:Props){const stage=stageOf(draft,profile,canPublish);const[publishState,publishAction,publishPending]=useActionState(requestOnboardingPublication,initial);const[custom,setCustom]=useState(draft?.specialty_code==="custom");const activeBilling=billing?.billing_state==="ACTIVE"||billing?.billing_state==="GRACE";
  return <div className="pc-onboarding-form" data-stage={stage}>
    <div className="pc-onboarding-progress" aria-label="Progresso"><span data-complete><i><Check/></i><small>Conta</small></span><span data-active><i>2</i><small>Seu site</small></span><span data-complete={stage==="published"||undefined}><i>3</i><small>Publicar</small></span><span><i>4</i><small>Primeiro aluno</small></span></div>
    {stage==="identity"?<SubmitForm action={saveOnboardingIdentity} submit="Continuar" multipart><header><span>Seu site começa por você</span><h1>Sua identidade profissional</h1><p>Use uma foto nítida e o nome que seus alunos reconhecem.</p></header><label className="pc-photo-input">Foto profissional<input name="image" type="file" accept="image/jpeg,image/png,image/webp"/><small>JPG, PNG ou WebP · até 5 MB</small></label><label>Nome *<input name="display_name" defaultValue={draft?.display_name??""} required minLength={2} maxLength={100} autoComplete="name"/></label><label>Nome profissional<input name="professional_name" defaultValue={draft?.professional_name??""} maxLength={100}/></label></SubmitForm>:null}
    {stage==="professional"?<SubmitForm action={saveOnboardingProfessional} submit="Continuar"><header><span>Seu trabalho</span><h1>Como você ajuda seus alunos?</h1></header><label>Especialidade principal<select name="specialty_code" defaultValue={draft?.specialty_code??"hypertrophy"} onChange={e=>setCustom(e.target.value==="custom")}><option value="hypertrophy">Hipertrofia</option><option value="weight_loss">Emagrecimento</option><option value="strength">Força</option><option value="conditioning">Condicionamento</option><option value="running">Corrida</option><option value="mobility">Mobilidade</option><option value="custom">Outra especialidade</option></select></label>{custom?<label>Qual especialidade? *<input name="custom_specialty" defaultValue={draft?.specialty_label??""} required minLength={2} maxLength={120}/></label>:null}<fieldset className="pc-mode-fieldset"><legend>Formato de atendimento</legend><div>{[["online","Online"],["presencial","Presencial"],["both","Híbrido"]].map(([value,label])=><label key={value}><input type="radio" name="service_mode" value={value} defaultChecked={(draft?.service_mode??"both")===value} required/><span>{label}</span></label>)}</div></fieldset><label>Cidade <input name="city" defaultValue={draft?.city??""} maxLength={120} autoComplete="address-level2"/></label><label>CREF <input name="cref" defaultValue={draft?.cref??""} maxLength={60}/></label></SubmitForm>:null}
    {stage==="social"?<SubmitForm action={saveOnboardingSocial} submit="Escolher estilo"><header><span>Contato direto</span><h1>Onde seus alunos encontram você?</h1><p>WhatsApp é necessário. Os demais canais podem ficar para depois.</p></header><label>WhatsApp *<input name="whatsapp" type="tel" inputMode="tel" autoComplete="tel" defaultValue={draft?.whatsapp??""} required placeholder="55 11 99999-9999"/></label><label>Instagram <input name="instagram" defaultValue={draft?.instagram??""} placeholder="@seuperfil" maxLength={120}/></label><label>TikTok <input name="tiktok" defaultValue={draft?.tiktok??""} placeholder="@seuperfil" maxLength={160}/></label><label>YouTube <input name="youtube" type="text" defaultValue={draft?.youtube??""} placeholder="@seucanal ou URL" maxLength={360}/></label></SubmitForm>:null}
    {stage==="template"?<SubmitForm action={saveOnboardingTemplate} submit="Gerar meu site"><header><span>Escolha visual</span><h1>Qual estilo representa seu trabalho?</h1><p>São os mesmos templates usados no site publicado.</p></header><div className="pc-template-options">{templateCatalog.filter(t=>t.availability.production).map((template,index)=><label key={template.id} className="pc-template-choice" data-template={template.id}><input type="radio" name="template_id" value={template.id} defaultChecked={(draft?.template_id??"template_01")==template.id}/><i aria-hidden="true">{String(index+1).padStart(2,"0")}</i><strong>{template.name}</strong><small>{template.description}</small></label>)}</div></SubmitForm>:null}
    {stage==="ready"&&profile?<section className="pc-onboarding-step pc-onboarding-ready"><header><span>Primeiro momento de valor</span><h1>Seu site está pronto</h1><p>Veja o site real com seus dados antes de decidir publicar.</p></header><div className="pc-real-preview"><iframe title="Prévia real do seu site" src={`/site-preview?template=${profile.template_id}`}/></div><form action={publishAction}><button className="pc-onboarding-primary" disabled={publishPending}>{publishPending?"Preparando…":"Publicar meu site"}</button></form>{publishState.message?<p role="status" className="form-message">{publishState.message}</p>:null}<a className="pc-onboarding-secondary" href="/dashboard/site">Continuar editando</a></section>:null}
    {stage==="trial"?<section className="pc-onboarding-step pc-trial"><header><span>Desbloqueie a publicação</span><h1>7 dias de PPerfil PRO</h1><p>Seu site já está salvo. Ative o trial para colocá-lo no ar.</p></header><div className="pc-trial-price"><strong>R$ 0</strong><span>hoje</span></div><ul><li>Cartão necessário para iniciar</li><li>7 dias grátis</li><li>R$ 59,90/mês depois</li><li>Cancele antes do fim do trial e não pague nada</li></ul><CheckoutButton/><small>A publicação só acontece após confirmação autoritativa do Stripe. Retornar do Checkout não ativa o PRO.</small></section>:null}
    {stage==="syncing"?<section className="pc-onboarding-step"><header><span>Confirmação segura</span><h1>Estamos confirmando sua ativação</h1><p>O Stripe está sendo reconciliado com seu acesso. Atualize esta página em instantes.</p></header><a className="pc-onboarding-primary" href="/onboarding">Verificar novamente</a></section>:null}
    {stage==="published"&&profile&&publicUrl?<section className="pc-onboarding-step pc-published"><header><span>{activeBilling?"PRO ativo":"Publicação disponível"}</span><h1>Seu site está publicado</h1><p>Agora seus alunos já podem encontrar você.</p></header><div className="pc-public-link"><strong>{publicUrl}</strong><button type="button" onClick={()=>navigator.clipboard.writeText(publicUrl)}><Copy/>Copiar</button></div><div className="pc-publish-actions"><a href={publicUrl} target="_blank" rel="noreferrer"><ExternalLink/>Abrir site</a><a href={`https://wa.me/?text=${encodeURIComponent(`Conheça meu site: ${publicUrl}`)}`} target="_blank" rel="noreferrer"><Share2/>Compartilhar no WhatsApp</a></div><p className="pc-honest-note">Adicione este link à sua bio do Instagram ou TikTok.</p>{hasStudentActivity?<a className="pc-onboarding-primary" href="/dashboard">Ir para o Dashboard</a>:<div className="pc-first-student"><h2>Convide seu primeiro aluno</h2><p>A entrega por e-mail ainda não está ativa. Crie o convite e compartilhe o link gerado.</p><InviteStudentForm/></div>}</section>:null}
  </div>;
}
