"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { acceptStudentInvitation, createNamedInvitation, deactivateStudent, revokeStudentInvitation } from "@/lib/supabase/students";
import { convertLead, rejectLead } from "@/lib/supabase/leads";
import { isDemoWorkspaceRequest } from "@/lib/demo/workspace";
import { sendTransactionalEmail } from "@/lib/email/provider";
import { buildStudentInvitationEmail } from "@/lib/email/student-invitation";
import { STUDENT_APP_HOME } from "@/lib/navigation/student-invitation";
import { findOwnerProfile } from "@/lib/supabase/trainers";

export type StudentActionState={ok?:boolean;message?:string;inviteUrl?:string;nextHref?:string;demoSimulation?:boolean;invitationCreated?:boolean;emailDelivery?:"email_sent"|"email_failed"|"not_attempted"};
const invitationUrl=(token:string)=>{if(!/^[a-f0-9]{64}$/.test(token))throw new Error("invitation_invalid");const configured=process.env.NEXT_PUBLIC_SITE_URL?.trim();const base=configured||(process.env.NODE_ENV!=="production"?"http://localhost:3000":"");if(!base)throw new Error("site_url_not_configured");const origin=new URL(base);if(origin.protocol!=="https:"&&!(process.env.NODE_ENV!=="production"&&origin.protocol==="http:"))throw new Error("site_url_not_configured");return new URL(`/invite/${token}`,`${origin.origin}/`).toString()};
const validId=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const friendly=(error:unknown,fallback:string)=>{const message=error instanceof Error?error.message:String(error);if(message.includes("demo_workspace_read_only"))return"Workspace demo é somente leitura. Nenhum dado foi enviado ao Supabase.";if(message.includes("lead_email_required"))return"Este lead não possui e-mail para receber o convite.";if(message.includes("lead_not_actionable"))return"Este lead não está mais disponível para esta ação.";if(message.includes("invitation_not_available"))return"Este convite não está disponível para cancelamento.";if(message.includes("invitation_invalid"))return"Este convite não está disponível. Ele pode ter expirado, já ter sido usado ou pertencer a outro e-mail.";return fallback};

export async function rejectLeadAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const id=String(form.get("match_id")??"");if(!validId(id))return{message:"Lead inválido."};try{const demo=await isDemoWorkspaceRequest();await rejectLead(id);return{ok:true,message:demo?"Lead rejeitado nesta simulação local.":"Lead rejeitado.",demoSimulation:demo}}catch(error){return{message:friendly(error,"Não foi possível rejeitar o lead.")}}}
export async function convertLeadAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const id=String(form.get("match_id")??"");if(!validId(id))return{message:"Lead inválido."};try{const demo=await isDemoWorkspaceRequest();const invite=await convertLead(id);return demo?{ok:true,message:"Lead convertido na simulação local. O registro do aluno já está disponível.",nextHref:`/dashboard/students/${invite.conversionId}`,demoSimulation:true}:{ok:true,message:"Lead convertido. Compartilhe o link de convite abaixo.",inviteUrl:invitationUrl(invite.token)}}catch(error){return{message:friendly(error,"Não foi possível converter o lead.")}}}
export async function inviteStudentAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const name=String(form.get("name")??"").trim(),email=String(form.get("email")??"").trim().toLowerCase();if(name.length<1||name.length>120||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return{message:"Informe um nome e um e-mail válidos."};try{const demo=await isDemoWorkspaceRequest();const invite=await createNamedInvitation(name,email);revalidatePath("/dashboard/students");if(demo)return{ok:true,invitationCreated:true,emailDelivery:"not_attempted",message:"Convite criado nesta simulação local.",inviteUrl:invitationUrl(invite.token),demoSimulation:true};let url:string;try{url=invitationUrl(invite.token)}catch{return{ok:true,invitationCreated:true,emailDelivery:"email_failed",message:"Convite criado, mas o e-mail não pôde ser enviado. Configure a URL pública para compartilhar o convite."}}let trainerName:string|null=null;try{trainerName=(await findOwnerProfile())?.display_name??null}catch{trainerName=null}try{const delivery=await sendTransactionalEmail(buildStudentInvitationEmail({invitationId:invite.invitationId,recipientEmail:email,trainerName,inviteUrl:url,expiresAt:invite.expiresAt}));return delivery.status==="sent"?{ok:true,invitationCreated:true,emailDelivery:"email_sent",message:"Convite criado e enviado.",inviteUrl:url}:{ok:true,invitationCreated:true,emailDelivery:"email_failed",message:"Convite criado, mas o e-mail não pôde ser enviado. Compartilhe o link manualmente.",inviteUrl:url}}catch{return{ok:true,invitationCreated:true,emailDelivery:"email_failed",message:"Convite criado, mas o e-mail não pôde ser enviado. Compartilhe o link manualmente.",inviteUrl:url}}}catch(error){return{message:friendly(error,"Não foi possível criar o convite.")}}}
export async function revokeInvitationAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const id=String(form.get("invitation_id")??"");if(!validId(id))return{message:"Convite inválido."};try{const demo=await isDemoWorkspaceRequest();await revokeStudentInvitation(id);return{ok:true,message:"Convite cancelado.",demoSimulation:demo}}catch(error){return{message:friendly(error,"Não foi possível cancelar o convite.")}}}
export async function deactivateStudentAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const id=String(form.get("relationship_id")??"");if(!validId(id))return{message:"Relacionamento inválido."};try{await deactivateStudent(id);revalidatePath("/dashboard/students");revalidatePath(`/dashboard/students/${id}`);return{ok:true,message:"Relacionamento desativado sem apagar o histórico."}}catch(error){return{message:friendly(error,"Não foi possível desativar este relacionamento.")}}}
export async function acceptInvitationAction(token:string,_state:StudentActionState,form:FormData):Promise<StudentActionState>{const name=String(form.get("name")??"").trim();if(!/^[a-f0-9]{64}$/.test(token)||name.length>120)return{message:"Este convite não está disponível."};try{await acceptStudentInvitation(token,name||undefined)}catch(error){return{message:friendly(error,"Não foi possível aceitar este convite.")}}redirect(STUDENT_APP_HOME)}
