"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { acceptStudentInvitation, createStudentInvitation, deactivateStudent, editInvitationEmail, recordInvitationDelivery, prepareInvitationResend, revokeStudentInvitation, type InvitationDeliveryStatus } from "@/lib/supabase/students";
import { convertLead, rejectLead } from "@/lib/supabase/leads";
import { isDemoWorkspaceRequest } from "@/lib/demo/workspace";
import { sendTransactionalEmail } from "@/lib/email/provider";
import { buildStudentInvitationEmail } from "@/lib/email/student-invitation";
import { STUDENT_APP_HOME } from "@/lib/navigation/student-invitation";
import { findOwnerProfile } from "@/lib/supabase/trainers";

export type StudentActionState={ok?:boolean;message?:string;inviteUrl?:string;nextHref?:string;demoSimulation?:boolean;invitationCreated?:boolean;emailDelivery?:InvitationDeliveryStatus|"not_attempted"};
const invitationUrl=(token:string)=>{if(!/^[a-f0-9]{64}$/.test(token))throw new Error("invitation_invalid");const configured=process.env.NEXT_PUBLIC_SITE_URL?.trim();const base=configured||(process.env.NODE_ENV!=="production"?"http://localhost:3000":"");if(!base)throw new Error("site_url_not_configured");const origin=new URL(base);if(origin.protocol!=="https:"&&!(process.env.NODE_ENV!=="production"&&origin.protocol==="http:"))throw new Error("site_url_not_configured");return new URL(`/invite/${token}`,`${origin.origin}/`).toString()};
const validId=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const friendly=(error:unknown,fallback:string)=>{const message=error instanceof Error?error.message:String(error);if(message.includes("demo_workspace_read_only"))return"Workspace demo é somente leitura. Nenhum dado foi enviado ao Supabase.";if(message.includes("invitation_resend_rate_limited"))return"Este convite foi reenviado recentemente. Aguarde um minuto.";if(message.includes("lead_email_required"))return"Este lead não possui e-mail para receber o convite.";if(message.includes("lead_not_actionable"))return"Este lead não está mais disponível para esta ação.";if(message.includes("invitation_not_available"))return"Este convite não está mais disponível.";if(message.includes("invitation_invalid"))return"Este convite não está disponível. Ele pode ter expirado, já ter sido usado ou pertencer a outro e-mail.";return fallback};

async function deliverInvitation(invite:{invitationId:string;token:string;expiresAt:string},email:string){let url:string;try{url=invitationUrl(invite.token)}catch{try{await recordInvitationDelivery(invite.invitationId,"delivery_failed",null)}catch{}return{ok:true,invitationCreated:true,emailDelivery:"delivery_failed",message:"Convite criado, mas o e-mail não pôde ser enviado."} satisfies StudentActionState}let trainerName:string|null=null;try{trainerName=(await findOwnerProfile())?.display_name??null}catch{trainerName=null}const delivery=await sendTransactionalEmail(buildStudentInvitationEmail({invitationId:invite.invitationId,recipientEmail:email,trainerName,inviteUrl:url,expiresAt:invite.expiresAt}));const status:InvitationDeliveryStatus=delivery.status==="sent"?"provider_accepted":delivery.reason==="provider_rejected"?"provider_rejected":delivery.reason==="network_error"?"delivery_unknown":"delivery_failed";const providerMessageId=delivery.status==="sent"?delivery.providerMessageId:null;try{await recordInvitationDelivery(invite.invitationId,status,providerMessageId)}catch{}const message=status==="provider_accepted"?"Convite criado. O provedor aceitou o e-mail para entrega.":status==="provider_rejected"?"Convite criado, mas o provedor recusou o e-mail.":status==="delivery_unknown"?"Convite criado. Não foi possível confirmar a entrega do e-mail.":"Convite criado, mas o e-mail não pôde ser enviado.";return{ok:true,invitationCreated:true,emailDelivery:status,message,inviteUrl:url} satisfies StudentActionState}

export async function rejectLeadAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const id=String(form.get("match_id")??"");if(!validId(id))return{message:"Lead inválido."};try{const demo=await isDemoWorkspaceRequest();await rejectLead(id);return{ok:true,message:demo?"Lead rejeitado nesta simulação local.":"Lead rejeitado.",demoSimulation:demo}}catch(error){return{message:friendly(error,"Não foi possível rejeitar o lead.")}}}
export async function convertLeadAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const id=String(form.get("match_id")??"");if(!validId(id))return{message:"Lead inválido."};try{const demo=await isDemoWorkspaceRequest();const invite=await convertLead(id);return demo?{ok:true,message:"Lead convertido na simulação local. O registro do aluno já está disponível.",nextHref:`/dashboard/students/${invite.conversionId}`,demoSimulation:true}:{ok:true,message:"Lead convertido. Compartilhe o link de convite abaixo.",inviteUrl:invitationUrl(invite.token)}}catch(error){return{message:friendly(error,"Não foi possível converter o lead.")}}}
export async function inviteStudentAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const email=String(form.get("email")??"").trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>320)return{message:"Informe um e-mail válido."};try{const demo=await isDemoWorkspaceRequest();const invite=await createStudentInvitation(email);revalidatePath("/dashboard/students");if(demo)return{ok:true,invitationCreated:true,emailDelivery:"not_attempted",message:"Convite criado nesta simulação local.",inviteUrl:invitationUrl(invite.token),demoSimulation:true};return await deliverInvitation(invite,email)}catch(error){return{message:friendly(error,"Não foi possível criar o convite.")}}}
export async function resendInvitationAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const id=String(form.get("invitation_id")??"");if(!validId(id))return{message:"Convite inválido."};try{const invite=await prepareInvitationResend(id);const result=await deliverInvitation(invite,invite.email);revalidatePath("/dashboard/students");return result}catch(error){return{message:friendly(error,"Não foi possível reenviar o convite.")}}}
export async function editInvitationEmailAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const id=String(form.get("invitation_id")??""),email=String(form.get("email")??"").trim().toLowerCase();if(!validId(id)||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>320)return{message:"Informe um e-mail válido."};try{const edited=await editInvitationEmail(id,email);if(edited.status==="UNCHANGED")return{ok:true,message:"O e-mail não mudou. Nenhum novo envio foi feito."};const result=await deliverInvitation(edited,edited.email);revalidatePath("/dashboard/students");return result}catch(error){return{message:friendly(error,"Não foi possível editar o convite.")}}}
export async function revokeInvitationAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const id=String(form.get("invitation_id")??"");if(!validId(id))return{message:"Convite inválido."};try{const demo=await isDemoWorkspaceRequest();await revokeStudentInvitation(id);return{ok:true,message:"Convite cancelado.",demoSimulation:demo}}catch(error){return{message:friendly(error,"Não foi possível cancelar o convite.")}}}
export async function deactivateStudentAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const id=String(form.get("relationship_id")??"");if(!validId(id))return{message:"Relacionamento inválido."};try{await deactivateStudent(id);revalidatePath("/dashboard/students");revalidatePath(`/dashboard/students/${id}`);return{ok:true,message:"Relacionamento desativado sem apagar o histórico."}}catch(error){return{message:friendly(error,"Não foi possível desativar este relacionamento.")}}}
export async function acceptInvitationAction(token:string,_state:StudentActionState,form:FormData):Promise<StudentActionState>{const name=String(form.get("name")??"").trim();if(!/^[a-f0-9]{64}$/.test(token)||name.length>120)return{message:"Este convite não está disponível."};try{await acceptStudentInvitation(token,name||undefined)}catch(error){return{message:friendly(error,"Não foi possível aceitar este convite.")}}redirect(STUDENT_APP_HOME)}
