"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { acceptStudentInvitation, createNamedInvitation, deactivateStudent } from "@/lib/supabase/students";
import { convertLead, rejectLead } from "@/lib/supabase/leads";
import { isDemoWorkspaceRequest } from "@/lib/demo/workspace";
import { STUDENT_APP_HOME } from "@/lib/navigation/student-invitation";

export type StudentActionState={ok?:boolean;message?:string;inviteUrl?:string;nextHref?:string;demoSimulation?:boolean};
const invitationUrl=(token:string)=>`${process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/,"")||"http://localhost:3000"}/invite/${token}`;
const validId=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const friendly=(error:unknown,fallback:string)=>{const message=error instanceof Error?error.message:String(error);if(message.includes("demo_workspace_read_only"))return"Workspace demo é somente leitura. Nenhum dado foi enviado ao Supabase.";if(message.includes("lead_email_required"))return"Este lead não possui e-mail para receber o convite.";if(message.includes("lead_not_actionable"))return"Este lead não está mais disponível para esta ação.";if(message.includes("invitation_invalid"))return"Este convite é inválido, expirou ou pertence a outro e-mail.";return fallback};

export async function rejectLeadAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const id=String(form.get("match_id")??"");if(!validId(id))return{message:"Lead inválido."};try{const demo=await isDemoWorkspaceRequest();await rejectLead(id);return{ok:true,message:demo?"Lead rejeitado nesta simulação local.":"Lead rejeitado.",demoSimulation:demo}}catch(error){return{message:friendly(error,"Não foi possível rejeitar o lead.")}}}
export async function convertLeadAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const id=String(form.get("match_id")??"");if(!validId(id))return{message:"Lead inválido."};try{const demo=await isDemoWorkspaceRequest();const invite=await convertLead(id);return demo?{ok:true,message:"Lead convertido na simulação local. O registro do aluno já está disponível.",nextHref:`/dashboard/students/${invite.conversionId}`,demoSimulation:true}:{ok:true,message:"Lead convertido. Compartilhe o link de convite abaixo.",inviteUrl:invitationUrl(invite.token)}}catch(error){return{message:friendly(error,"Não foi possível converter o lead.")}}}
export async function inviteStudentAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const name=String(form.get("name")??"").trim(),email=String(form.get("email")??"").trim().toLowerCase();if(name.length<1||name.length>120||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return{message:"Informe um nome e um e-mail válidos."};try{const demo=await isDemoWorkspaceRequest();const invite=await createNamedInvitation(name,email);revalidatePath("/dashboard/students");return{ok:true,message:demo?"Convite criado nesta simulação local.":"Convite criado. Em desenvolvimento, compartilhe este link com o aluno.",inviteUrl:invitationUrl(invite.token),demoSimulation:demo}}catch(error){return{message:friendly(error,"Não foi possível criar o convite.")}}}
export async function deactivateStudentAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const id=String(form.get("relationship_id")??"");if(!validId(id))return{message:"Relacionamento inválido."};try{await deactivateStudent(id);revalidatePath("/dashboard/students");revalidatePath(`/dashboard/students/${id}`);return{ok:true,message:"Relacionamento desativado sem apagar o histórico."}}catch(error){return{message:friendly(error,"Não foi possível desativar este relacionamento.")}}}
export async function acceptInvitationAction(_state:StudentActionState,form:FormData):Promise<StudentActionState>{const token=String(form.get("token")??""),name=String(form.get("name")??"").trim();if(!/^[a-f0-9]{64}$/.test(token)||name.length>120)return{message:"Convite inválido."};try{await acceptStudentInvitation(token,name||undefined)}catch(error){return{message:friendly(error,"Não foi possível aceitar este convite.")}}redirect(STUDENT_APP_HOME)}
